// https://developers.google.com/maps/documentation/directions/intro#StatusCodes
module.exports = {
  OK: "OK",
  NOT_FOUND: "NOT_FOUND",
  ZERO_RESULTS: "ZERO_RESULTS",
  MAX_ROUTE_LENGTH_EXCEEDED: "MAX_ROUTE_LENGTH_EXCEEDED",
  INVALID_REQUEST: "INVALID_REQUEST",
  OVER_DAILY_LIMIT: "OVER_DAILY_LIMIT",
  OVER_QUERY_LIMIT: "OVER_QUERY_LIMIT",
  REQUEST_DENIED: "REQUEST_DENIED",
  UNKNOWN_ERROR: "UNKNOWN_ERROR"
}